
delete from mms.session_logging;
delete from mms.seqno_control;
delete from mms.query_columns_record;

delete from mms.dmm_asset_supported_function;
delete from mms.dmm_asset_supported_comm;
delete from mms.dmm_asset_type_company;
delete from mms.dmm_asset_type;
delete from mms.dmm_repository_child;
delete from mms.dmm_repository;

delete from mms.bim_merchant_header;
delete from mms.bim_merchant_bank;
delete from mms.bim_merchant;

delete from mms.apk_management;

delete from mms.adm_system_logging_history;
delete from mms.adm_system_logging;
delete from mms.adm_pwd_history;
delete from mms.adm_user_role;

delete from mms.adm_role_permission;
delete from mms.adm_user;
delete from mms.adm_role;

delete from mms.white_lists;
delete from mms.bim_mid_manage;
delete from mms.mms_transaction_history;

delete from mms.switching_company;
delete from mms.bim_company_type;
delete from mms.bim_company;

delete from mms.switching_datasource;
delete from mms.server_info;

alter table mms.server_info add `enable_flag` varchar(1) DEFAULT 'N';

INSERT INTO mms.adm_role
(ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_DESC, `ATTRIBUTE`, WORK_FLOW_ROLE, CREATED_BY_ID, CREATED_BY_NAME, CREATED_DATE, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'SYSTEM', 'CSNA group', 'CSNA', 'SYSTEM', 'DANGEROUS', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01010_ADD', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01010_DELETE', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01010_EDIT', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01010_QUERY', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01020_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01030_ADD', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01030_DELETE', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01030_DETAIL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01030_QUERY', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01040_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01060_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01070_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'ADM01090_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'AMM06020_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'AMM06030_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'BIM02010_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'BIM02070_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'BIM02080_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'BIM02110_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'DMM03010_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'DMM03011_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'MMS06010_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'MMS06020_ALL', NULL, NULL, NULL);
INSERT INTO mms.adm_role_permission
(ROLE_ID, PERMISSION_ID, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE)
VALUES('1000000000-0001', 'MMS06030_ALL', NULL, NULL, NULL);

INSERT INTO mms.bim_company
(COMPANY_ID, COMPANY_CODE, SHORT_NAME, UNITY_NUMBER, INVOICE_HEADER, LEADER, TEL, FAX, APPLY_DATE, PAY_DATE, CONTACT, CONTACT_TEL, CONTACT_EMAIL, CUSTOMER_CODE, COMPANY_EMAIL, DTID_TYPE, AUTHENTICATION_TYPE, ADDRESS_LOCATION, ADDRESS, INVOICE_ADDRESS_LOCATION, INVOICE_ADDRESS, REMARK, CREATED_BY_ID, CREATED_BY_NAME, CREATED_DATE, UPDATED_BY_ID, UPDATED_BY_NAME, UPDATED_DATE, DELETED, IS_NOTIFY_AO, ADDRESS_CITY, INVOICE_ADDRESS_CITY)
VALUES('1000000000-0001', 'BWA', 'BWA', '', '', '', '', '', '', '', '', '', '', '', '', 'SAME', 'IATOMS_AUTHEN', '', '', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'N', 'N', '', NULL);

INSERT INTO mms.bim_company_type
(COMPANY_ID, COMPANY_TYPE)
VALUES('1000000000-0001', 'CUSTOMER');
INSERT INTO mms.bim_company_type
(COMPANY_ID, COMPANY_TYPE)
VALUES('1000000000-0001', 'HARDWARE_VENDOR');
INSERT INTO mms.bim_company_type
(COMPANY_ID, COMPANY_TYPE)
VALUES('1000000000-0001', 'MAINTENANCE_VENDOR');